version: "2"

services:
  connected vehicle software:
    image: kyraatma/icedge:latest
    network_mode: host
    service_name:        
        logging:
            options:
                max-size: "50m"
    