version: "2"

services:
  ic_pcap_capture:
    image: kyraatma/ic_pcap_capture
    environment:
      - IFACE=${IFACE}
      - FILTER=${FILTER}
      - DURATION=${DURATION}
      - FILENAME=${FILENAME}
    volumes:
      - ${PWD}:/data
    network_mode: host  
    tty: true
