version: "2"

services:
  siemens-rsu-initializer:
    ports:
    - 80:80
    - 4001:4001
    command:
    - /bin/bash
    image: kyraatma/siemens-rsu-initializer
    logging:
      driver: json-file
      options:
        max-size: 50m
    restart: always
    environment:
      - RSU_URL_ARRAY=${RSU_URL_ARRAY}
      - MQTT_URL=${MQTT_URL}
      - RECONNECT_INTERVAL=${RECONNECT_INTERVAL}
      - PORT=${PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - LOG_LEVEL=${LOG_LEVEL}
    network_mode: host
    tty: true
