.catalog:
  name: Siemens RSU Driver
  version: latest
  uuid: Siemens RSU Driver
  questions:
  - variable: RSU_URL_ARRAY
    description: 'RSU server url'
    label: 'server url'
    required: true
    default: [\"wss://10.233.8.148:3600/xfer\"] 
    type: string
  - variable: MQTT_URL
    description: 'MQTT server URL'
    label: 'MQTT url'
    required: true
    default: mqtt://10.233.8.143:1883
    type: string
  - variable: RECONNECT_INTERVAL
    description: 'RECONNECT_INTERVAL'
    label: 'RECONNECT_INTERVAL'
    required: true
    default: 2000
    type: int
  - variable: PORT
    description: 'PORT'
    label: 'PORT'
    required: true
    default: 4001
    type: int
  - variable: MQTT_TOPIC
    description: 'topic name'
    label: 'topic'
    required: true
    default: decoder
    type: string
  - variable: LOG_LEVEL
    description: 'LOG_LEVEL'
    label: 'LOG_LEVEL'
    required: false
    default: OFF
    type: string
    options:
      - ALL
      - TRACE
      - DEBUG
      - INFO
      - WARN
      - ERROR
      - FATAL
      - MARK
      - OFF