.catalog:
  name: Connected Device Software
  version: latest
  uuid: Connected Device Software-0  
  questions:
  - variable: PORT
    port: ttyS1
    description: 'communication port'
    required: true
    default: ttyUSB0
    type: string
  
