version: "2"

services:
  ic_iot_sensor:
    command:
    - /bin/bash
    image: kyraatma/ic_iot_sensor
    environment:
      - SERVER=${SERVER}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
      - TOPIC=${TOPIC}
    logging:
      driver: json-file
      options:
        max-size: 50m
    privileged: true
    volumes:
    - /dev/radar:/dev/radar
    network_mode: bridge
    tty: true
